{% set name = "quera-ahs-utils" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quera-ahs-utils-{{ version }}.tar.gz
  sha256: c63e1a8cae1b68914518586883047ca24d61a62c8b16af9ece9f1b320cf6bf84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - amazon-braket-sdk
    - amazon-braket-schemas
    - networkx
    - numpy
    - pydantic
    - matplotlib-base

test:
  imports:
    - quera_ahs_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QuEraComputing/quera-ahs-utils
  summary: Various tools to interact with Braket Analog Hamiltonian Simulation
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://queracomputing.github.io/quera-ahs-utils/

extra:
  recipe-maintainers:
    - weinbe58
