{% set name = "quera-ahs-utils" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quera-ahs-utils-{{ version }}.tar.gz
  sha256: 19a2ed8dab95e31d080015fad130dce0fb776b2618e8e46ef4569b095a75d2b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - amazon-braket-sdk
    - networkx
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - quera_ahs_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QuEraComputing/quera-ahs-utils
  summary: Various tools to interact with Braket Analog Hamiltonian Computing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - weinbe58
