{% set name = "quera-ahs-utils" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quera-ahs-utils-{{ version }}.tar.gz
  sha256: e59d935a5e9e2a3437f467481f92fd24f8be1bb8d0848c8fdd8cff9377566267

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - amazon-braket-sdk
    - networkx
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - quera_ahs_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QuEraComputing/quera-ahs-utils
  summary: Various tools to interact with Braket Analog Hamiltonian Simulation
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://queracomputing.github.io/quera-ahs-utils/

extra:
  recipe-maintainers:
    - weinbe58
