{% set name = "quera-ahs-utils" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quera-ahs-utils-{{ version }}.tar.gz
  sha256: e6a5e64ec7259cb39fa5b8de391745b4835025af9ea68b3050453321d2f423a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - amazon-braket-sdk
    - amazon-braket-schemas
    - networkx
    - numpy
    - pydantic
    - matplotlib-base

test:
  imports:
    - quera_ahs_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QuEraComputing/quera-ahs-utils
  summary: Various tools to interact with Braket Analog Hamiltonian Simulation
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://queracomputing.github.io/quera-ahs-utils/

extra:
  recipe-maintainers:
    - weinbe58
